services:
  db:
    container_name: reactxnet_db
    image: postgres:15.2-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: reactxnet
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
volumes:
  db_data:
    driver: local