# fly.toml app configuration file generated for cool-sun-4098 on 2023-04-24T20:40:56+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cool-sun-4098"
primary_region = "arn"

[build]
  image = "azdanov/reactxnet:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[checks]
  [checks.alive]
    type = "tcp"
    interval = "15s"
    timeout = "2s"
    grace_period = "5s"
